In [2]:
import numpy as np

In [3]:
#Question 1
np.__version__

'1.21.5'

In [4]:
import pandas as pd

In [6]:
df = pd.read_csv ('cars_data.csv')

In [7]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [12]:
# Question 2: How many records are in the dataset?
df.shape

(11914, 16)

In [22]:
#Question 3: Who are the most frequent car manufacturers (top-3) according to the dataset?
df["Make"].value_counts().head(3)

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

In [28]:
#Question 4: What's the number of unique Audi car models in the dataset?
audi_df = df[df["Make"] == "Audi"]

audi_df["Model"].nunique()

34

In [35]:
#Question 5: How many columns in the dataset have missing values?
num_columns = (df.isnull().sum() != 0).sum()
num_columns

5

In [39]:
#Question 6
#1.Find the median value of "Engine Cylinders" column in the dataset.
df["Engine Cylinders"].median()

6.0

In [49]:
#2. Next, calculate the most frequent value of the same "Engine Cylinders"
mode = df["Engine Cylinders"].mode()

0    5.0
Name: Engine Cylinders, dtype: float64

In [72]:
#3. Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
df['Engine Cylinders'] = df['Engine Cylinders'].fillna(df['Engine Cylinders'].mode())

In [74]:
new_median = df["Engine Cylinders"].median()
new_median

6.0

In [ ]:
#The median did not change

In [86]:
#7
lotus_cars = df[df["Make"] == "Lotus"]
new_lotus_cars = lotus_cars[["Engine HP", "Engine Cylinders"]]

In [89]:
new_data = new_lotus_cars.drop_duplicates()
new_data

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [92]:
X = new_data.to_numpy()

In [103]:
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [93]:
XT = X.transpose()

In [102]:
XT

array([[189., 218., 217., 350., 400., 276., 345., 257., 240.],
       [  4.,   4.,   4.,   8.,   6.,   6.,   6.,   4.,   4.]])

In [110]:
XTX = XT.dot(X)

In [111]:
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [112]:
inverted_XTX = np.linalg.inv(XTX)

In [113]:
inverted_XTX

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [114]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])

In [115]:
x1 = np.dot(inverted_XTX,XT)

In [116]:
x1

array([[-1.31950096e-03,  2.84443321e-04,  2.29134897e-04,
        -4.18763778e-03,  4.46417989e-03, -2.39406462e-03,
         1.42221660e-03,  2.44147184e-03,  1.50122864e-03],
       [ 8.60893170e-02,  7.36567735e-04,  3.67976598e-03,
         2.54588185e-01, -2.13748621e-01,  1.51207962e-01,
        -5.18727169e-02, -1.14048164e-01, -6.40137937e-02]])

In [117]:
w = np.dot(x1,y)

In [118]:
w

array([  4.59494481, -63.56432501])